"""empty message

Revision ID: 988ed462d3ec
Revises: 
Create Date: 2024-10-08 18:27:05.228514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988ed462d3ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mana_cost', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('power_toughness', sa.String(length=10), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('set_name', sa.String(length=3), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number', 'set_name', name='unique_card_in_set')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_name'))

    op.drop_table('cards')
    # ### end Alembic commands ###
